### ISSUE TITLE
ISAPI ... and maybe SDK?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/hikvision_client#2]
You're focussing on the ISAPI , I think that's probably a good idea as it's the one we use for most commands. Great.

Just as an FYI, in case you were not aware, there is also the "Server Port" or "SDK" commands which are less well documented but cover most of the same features , I think.

We found the SDK reboot command to be very useful in a scenario where we found the HTTP port died but SDK port was still responsive. This code still exists, I think (@azharmalik3 would know where it is). 

In a similar vein, an argument could also be made to offer OnVIF compliant commands. I see no onvif library for elixir. I think we also use some onvif compatible commands.

**Comment by azharmalik3** [comment]
We had SDK reboot in our codebase but later removed it because we were not using SDK reboot.

https://github.com/evercam/evercam-backend/commit/b8dfc3b020b26907b59fb56bf1e65dc9aacb6267#diff-438b9ed7032b8cc314254f98c15b076c9c5dd82bde99d00f154c3bff5b011c59R20

**Comment by marcoherbst** [comment]
Ok, right.

I'll close the issue, but I still think this client needs to more clearly reference the APIs & devices it is designed for. 

In this case, I think, it is the latest ISAPI versions of both Cameras & NVRs.
